version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      # App Configuration
      ENVIRONMENT: "production"
      DEBUG: "False"
      HOST: "0.0.0.0"
      PORT: "8000"
      
      # Security
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS:-7}
      
      # CORS
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      
      # Supabase Configuration
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
      OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS:-2000}
      OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE:-0.7}
      
      # Whisper Configuration
      WHISPER_MODEL: ${WHISPER_MODEL:-whisper-1}
      
      # Stripe Configuration
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PREMIUM_PRICE_ID: ${STRIPE_PREMIUM_PRICE_ID}
      
      # Backend URL for static file generation
      BACKEND_URL: ${BACKEND_URL}
      
      # Usage Limits
      FREE_NORMAL_CHAT_LIMIT: ${FREE_NORMAL_CHAT_LIMIT:-10}
      FREE_INTERVIEW_CHAT_LIMIT: ${FREE_INTERVIEW_CHAT_LIMIT:-5}
      PREMIUM_NORMAL_CHAT_LIMIT: ${PREMIUM_NORMAL_CHAT_LIMIT:-999999}
      PREMIUM_INTERVIEW_CHAT_LIMIT: ${PREMIUM_INTERVIEW_CHAT_LIMIT:-999999}
    volumes:
      - backend_uploads:/app/static/uploads

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8001}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8001/api/v1}
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_uploads: